# Travis CI Configuration

language: node_js
node_js:
  - "7"
  - "6"
# Installing rsvg-brunch requires a C++11 compiler and librsvg
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - librsvg2-dev
env:
  - CXX=g++-4.8
install:
  - npm install
  - npm install coveralls
script:
  - npm run lint
  - npm run coverage
after_success:
  - nyc report --reporter=text-lcov | coveralls
